### ISSUE TITLE
Asks for 'platform node' although this is specified in .esbuildrc.js

### ISSUE THREAD

**Issue by AlexJeffcott** [RtVision/mocha-esbuild#1]
// .esbuildrc.js
```javascript
import { buildSync } from 'esbuild';

buildSync({
	entryPoints: ['./src/index.ts'],
	bundle: true,
	write: true,
	minify: true,
	sourcemap: true,
	format: 'esm',
	platform: 'node',
	target: 'node16',
	outdir: './build',
});
```

```json
"test": "mocha-esbuild **/*.test.ts",
```

```typescript
import { performance, PerformanceObserver } from 'perf_hooks';

describe('performance test', () => {
	it('to work', () => {
		const obs = new PerformanceObserver((list) => {
			console.log(list.getEntries()[0].duration);
			performance.clearMarks();
			performance.clearMeasures();
			obs.disconnect();
		});
		obs.observe({ entryTypes: ['function'] });

		const wrapped = performance.timerify(() => console.log('hello'));
		wrapped()
	});
});
```
```shell
 src/__tests__/match/performance.test.ts:1:49: error: Could not resolve "perf_hooks" (use "platform: 'node'" when building for node)
    2 │ import { performance, PerformanceObserver } from 'perf_hooks';
     
```

**Comment by AlexJeffcott** [comment]
From looking at EsBuild.ts it seems that an options object as a defult export is expected.

Changing my 

```javascript
import { buildSync } from 'esbuild';
const opts = {
	entryPoints: ['./src/index.ts'],
	bundle: true,
	write: true,
	minify: true,
	sourcemap: true,
	format: 'esm',
	platform: 'node',
	target: 'node16',
	outdir: './build',
}

buildSync(opts);
export default opts
```

Works BUT only after commending the 'outdir' property as this conflicts with the `outfile` property which is set in Esbuild.ts

Do you accept prs?

**Comment by kalvenschraut** [comment]
I guess I am little confused, are you trying to generate your dist code and then having mocha-esbuild compile your test code? The way I wrote this is that you give mocha-esbuild your test entry point and that will pull in any dependencies those tests reference.

I specifically used this in a vuejs environment so if I had a test for a vuejs component I would import it in the test like below

```ts 
// test/SomeComponent.spec.ts
import SomeComponent from '@/components/SomeComponent.vue';

describe('Some component works'. () => {
    // test assertions
})
```

then  I will run mocha-esbuild by pointing it at that specific test file i.e. `mocha-esbuild test/SomeComponent.spec.ts` and it will compile both the test and the component since the test has the import to the component. Note it compiles these into 1 single file which then it tells mocha to run. 

Otherwise I am open to PRs depending on your use case if you can provide some more information.

**Comment by AlexJeffcott** [comment]
Thanks for your reply.

In my test I am using the node lib perf_hooks (`import { performance, PerformanceObserver } from 'perf_hooks';`) so I needed, I believe, to pass `platform: 'node'` as an esbuild option.

The esbuild docs appear to recommend using a function such as the below as 'config':
```
buildSync({
	entryPoints: ['./src/index.ts'],
	bundle: true,
	write: true,
	minify: true,
	sourcemap: true,
	format: 'esm',
	platform: 'node',
	target: 'node16',
	outdir: './build',
});
```

As far as I can tell, this does not work with mocha-esbuild as it expects an object to be exported.

Additionally, I think that while the 'outfile' is overridden, the 'outdir' is not, I think, so if you set it in your config it conflicts with the 'outfile' property.

```
let esbuildConfig : EsbuildOptions = {
  // need to have 1 central file to import the globs so create it
  stdin: {
	  contents: importFiles.map(f => `import '${f}';`).join('\n'),
	  resolveDir: process.cwd(),
	  sourcefile: 'Tests Entry Point'
  },
  bundle: true,
  outfile: outputFile
};
```

Essentially, I'd like to suggest also overriding the outdir esbuildOptions property, and adding sth to the docs about needed to export a config object for esbuild options.

Have I got it wrong?

**Comment by kalvenschraut** [comment]
Sorry for delay been a bit busy with work,

Guess I am most confused by the below

```ts
import { buildSync } from 'esbuild';
const opts = {
	entryPoints: ['./src/index.ts'],
	bundle: true,
	write: true,
	minify: true,
	sourcemap: true,
	format: 'esm',
	platform: 'node',
	target: 'node16',
	outdir: './build',
}

buildSync(opts);
export default opts
```

You shouldn't need to call buildSync in this file as mocha-esbuild will compile everything for you already. I see you are pointing it your index file in src. Does your test not import that file and use it directly? All your above code would really need to be is

```ts
export default {
	platform: 'node',
	target: 'node16',
}
```

plus whatever other options you want I guess.

**Comment by AlexJeffcott** [comment]
The above is my 'config' file for esbuild, I do not only use it for running mocha-esbuild.

Afaik, this is the way that esbuild recomends doing configuration files.

Is it fair to say that some valid esbuild configurations, placed in a `esbuild.js` will cause mocha-esbuild to misfunction?

**Comment by kalvenschraut** [comment]
hmmm okay I think I understand this a bit more easiest solution would to have a separate file for the moch-esbuild configuration of esbuilt

i.e. .moch-esbuildrc.js

```js
export default {
	platform: 'node',
	target: 'node16',
}
```

then run mocha-esbuild with the additional flag --esbuildConfig so based on your example it would like like this in package.json

```json
"test": "mocha-esbuild --esbuildConfig .mocha-esbuildrc.js **/*.test.ts",
```

* Note unless your package.json has type = module then you need to use .mjs extension instead of .js to use esm export syntax.
