### ISSUE TITLE
Getting this up-to-date, mirror mocha's exports, document the changes

### ISSUE THREAD

**Issue by DesignByOnyx** [RtVision/mocha-esbuild#3]
Hey, I discovered your package because it's pretty much the only thing on the internet that shows up for "mocha esbuild". Thanks so much for creating this! I see you haven't done much in a couple years and I was hoping I could help a little.

My goal is to have a package which can be used in place of all mocha invocations with no additional configuration. This package would use esbuild under the hood for running mocha tests.

Use cases:
- Npm scripts, command line, JS code, build pipelines, vscode extensions, etc.

Special considerations:
- We would probably need to ignore a few options, particularly any `require` strings which contain `ts-node` or `esbuild`. Other than that, this should attempt to maintain 100% API compatibility (it appears you have already done this).

More information:
Currently we are using the Mocha Test Explorer extension in VSCode, and this extension does a lot of monkey patching of mocha in order to work properly. It does this by importing the Mocha object and patching it. Unfortunately, your package does not have the same exports as the mocha package, thus breaking the extension. I imagine this would also break any attempt to `import/require` your package from code. I would really like to help you get this working, and I have a very suitable project for testing this.

Furthermore, it would be nice to document everything that went into making this package work so that members of the community can get in and more quickly contribute to this project or create variations of their own. If you can point me to some of the big pain points you encountered, I don't mind investigating and documenting it.

**Comment by kalvenschraut** [comment]
hey, apparently I don't get emails for this repo and I don't check on this much.

I don't use this at all anymore why this project has remained stale. I originally made this as I wanted a test runner to work with vite as I migrated to that off of webpack. As I used mocha-webpack prior to that migration. 

Since then [vitest](https://github.com/vitest-dev/vitest) has come out and I put my support into that project. As for this I don't intend to maintain this going forward.

As for issues that i hit when developing this, biggest one I could remember was getting the built asset from esbuild in a spot that would allow mocha to run tests against it. I ended up having to write the built file to a tmp file which then told mocha to read from it.

**Comment by DesignByOnyx** [comment]
I hear you - I'm in the process of moving us to vitest and don't really see much use for this anyways. The mocha team should pursue this if they want. Thanks.
